### ISSUE TITLE
Error fetching plugin: reference is not a tree

### ISSUE THREAD

**Issue by StephenClement** [meteor/cordova-plugin-meteor-webapp#17]
I am having an issue adding this as a plugin to Cordova. Not sure if this is happening to others or if it is just something I am doing wrong. When I go to compile I am getting the following error: 

`=> Errors executing Cordova commands:                                              
                                                                                   
   While adding plugin https://github.com/meteor/cordova-plugin-meteor-webapp.git#8bf95eed3f313299fc2de33658866278eea2cdc5 to Cordova
   project:
   Cordova error: Failed to fetch plugin https://github.com/meteor/cordova-plugin-meteor-webapp.git via git.
   Either there is a connection problems, or plugin spec is incorrect:
   Error: git: Command failed with exit code 128 Error output:
   fatal: reference is not a tree: 8bf95eed3f313299fc2de33658866278eea2cdc5
   at
   /Users/labnc_966/.meteor/packages/meteor-tool/.1.4.1_2.fpzmec++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/fetch.js:88:33
   at _rejected
   (/Users/labnc_966/.meteor/packages/meteor-tool/.1.4.1_2.fpzmec++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:844:24)
   at
   /Users/labnc_966/.meteor/packages/meteor-tool/.1.4.1_2.fpzmec++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:870:30
   at Promise.when
   (/Users/labnc_966/.meteor/packages/meteor-tool/.1.4.1_2.fpzmec++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:1122:31)
   at Promise.promise.promiseDispatch
   (/Users/labnc_966/.meteor/packages/meteor-tool/.1.4.1_2.fpzmec++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:788:41)
   at
   /Users/labnc_966/.meteor/packages/meteor-tool/.1.4.1_2.fpzmec++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:604:44
   at runSingle
   (/Users/labnc_966/.meteor/packages/meteor-tool/.1.4.1_2.fpzmec++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:137:13)
   at flush
   (/Users/labnc_966/.meteor/packages/meteor-tool/.1.4.1_2.fpzmec++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:125:13)
   at nextTickCallbackWith0Args (node.js:420:9)
   at process._tickCallback (node.js:349:13)
   (If the error message contains suggestions for a fix, note that this may not apply to the Meteor integration. You can try running again
   with the --verbose option to help diagnose the issue.)
`

From a little bit of research it looks like it might have to do with a submodule not being properly committed or something to that effect. Any help would be appreciated. Thanks!

**Comment by ichuanHung** [comment]
I have same error , when I run : 
  meteor  run ios-device  --verbose
here is the log : 
...
%% updated project successfully                                                    
%% Executing "after_plugin_add"  hook for all plugins.                             
Adding plugin https://github.com/meteor/cordova-plugin-meteor-webapp.git#8bf95eed3f313299fc2de33658866278eea2cdc5 to
Cordova project
%% Executing "before_plugin_add"  hook for all plugins.                            
%% Calling plugman.fetch on plugin "https://github.com/meteor/cordova-plugin-meteor-webapp.git#8bf95eed3f313299fc2de33658866278eea2cdc5"
%% Fetching plugin "https://github.com/meteor/cordova-plugin-meteor-webapp.git" via git clone
%% Running command: git clone https://github.com/meteor/cordova-plugin-meteor-webapp.git /var/folders/q0/zgc3cn5j5v776c29_5gwkbqh0000gn/T/git/1476947048588
%% Command finished with error code 0: git clone,https://github.com/meteor/cordova-plugin-meteor-webapp.git,/var/folders/q0/zgc3cn5j5v776c29_5gwkbqh0000gn/T/git/1476947048588
%% Running command: git checkout 8bf95eed3f313299fc2de33658866278eea2cdc5          
%% Command finished with error code 128: git checkout,8bf95eed3f313299fc2de33658866278eea2cdc5
=> Errors executing Cordova commands:                                              
                                                                                   
   While adding plugin                                                             
   https://github.com/meteor/cordova-plugin-meteor-webapp.git#8bf95eed3f313299fc2de33658866278eea2cdc5 to Cordova
   project:
   Cordova error: Failed to fetch plugin https://github.com/meteor/cordova-plugin-meteor-webapp.git via git.
   Either there is a connection problems, or plugin spec is incorrect:
   Error: git: Command failed with exit code 128 Error output:
   fatal: reference is not a tree: 8bf95eed3f313299fc2de33658866278eea2cdc5
   at
   /Users/user1/.meteor/packages/meteor-tool/.1.4.1_2.k6ctpo++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/fetch.js:88:33
   at _rejected
   (/Users/user1/.meteor/packages/meteor-tool/.1.4.1_2.k6ctpo++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:844:24)
   at
   /Users/user1/.meteor/packages/meteor-tool/.1.4.1_2.k6ctpo++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:870:30
   at Promise.when
   (/Users/user1/.meteor/packages/meteor-tool/.1.4.1_2.k6ctpo++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:1122:31)
   at Promise.promise.promiseDispatch
   (/Users/user1/.meteor/packages/meteor-tool/.1.4.1_2.k6ctpo++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:788:41)
   at
   /Users/user1/.meteor/packages/meteor-tool/.1.4.1_2.k6ctpo++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:604:44
   at runSingle
   (/Users/user1/.meteor/packages/meteor-tool/.1.4.1_2.k6ctpo++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:137:13)
   at flush
   (/Users/user1/.meteor/packages/meteor-tool/.1.4.1_2.k6ctpo++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/cordova-common/node_modules/q/q.js:125:13)
   at nextTickCallbackWith0Args (node.js:420:9)
   at process._tickCallback (node.js:349:13)
   (If the error message contains suggestions for a fix, note that this may not apply to the Meteor integration. You
   can try running again with the --verbose option to help diagnose the issue.)

/Users/user1/.meteor/packages/meteor-tool/.1.4.1_2.k6ctpo++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/isopackets/cordova-support/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^
ExitWithCode:1

Any help would be appreciated. Thanks a lot !

**Comment by jaydeebee** [comment]
This is bound to come up a bit - the version that people are reporting as failing is the one that'd been recommended as a workaround in [this thread on the Meteor forums](https://forums.meteor.com/t/ios-10-compatibility/26065/16).  With the branch's deletion, that rev disappeared.

The fix is to use a tagged release, (`@1.4.1`), rather than that git ref.
