### ISSUE TITLE
crosswalk android login

### ISSUE THREAD

**Issue by interfaith** [meteor/cordova-plugin-meteor-webapp#22]
deviceready has not fired after 5 seconds.
cordova.js:1178 Channel not fired: onDOMContentLoaded
webapp.js:68 Error: Error parsing asset manifest
at http://localhost:12168/plugins/cordova-plugin-meteor-webapp/www/webapp_local_server.js:36:21
at Object.callbackFromNative (http://localhost:12168/cordova.js:293:58)
at processMessage (http://localhost:12168/cordova.js:1081:17)
at processMessages (http://localhost:12168/cordova.js:1104:9)
at pollOnce (http://localhost:12168/cordova.js:973:9)
at pollOnceFromOnlineEvent (http://localhost:12168/cordova.js:960:5)(anonymous function) @ webapp.js:68

**Comment by hwillson** [comment]
There have been many new releases of Meteor since this issue was created. Please try using a more recent version (>= 1.6.x), and post back if you're still encountering issues. Thanks!
