### ISSUE TITLE
ENOENT, no such file or directory Bridging-Header.h

### ISSUE THREAD

**Issue by lpender** [meteor/cordova-plugin-meteor-webapp#6]
Hi! 

I get this issue when trying to compile my Meteor 1.3 app.

```
% Failed to install 'cordova-plugin-meteor-webapp':Error: ENOENT, no such file or directory '/Users/lpender/dev/mine/flare/.meteor/local/cordova-build/platforms/ios/Flare/Bridging-Header.h'
  at Object.fs.openSync (fs.js:439:18)
  at Object.fs.readFileSync (fs.js:290:15)
  at module.exports (/Users/lpender/dev/mine/flare/.meteor/local/cordova-build/plugins/cordova-plugin-meteor-webapp/scripts/iosAddBridgingHeader.js:21:17)
  at runScriptViaModuleLoader (/Users/lpender/.meteor/packages/meteor-tool/.1.3.2_4.103hozl++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:167:18)
  at runScript (/Users/lpender/.meteor/packages/meteor-tool/.1.3.2_4.103hozl++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/Users/lpender/.meteor/packages/meteor-tool/.1.3.2_4.103hozl++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
  at /Users/lpender/.meteor/packages/meteor-tool/.1.3.2_4.103hozl++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:810:14
  at flush (/Users/lpender/.meteor/packages/meteor-tool/.1.3.2_4.103hozl++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:458:13)
```

Any ideas?

Thanks

**Comment by AliMamed** [comment]
Hi! I just had the same problem. I've just deleted `.meteor/local/cordova-build` and reran the app

**Comment by lpender** [comment]
That worked for me too

**Comment by mvgalle** [comment]
Had a similar problem. try: 
`meteor reset`

and then re run your app.

**Comment by povesteam** [comment]
I had the same problem, and resolved it by ensuring that the **meteor application folder** is exactly the same as the `name` property in `mobile-config.js` `App.info`.

Found the fix by running `meteor build` with the `--verbose` option, and the complaint was using part of the Bridging-Header.h file from the `mobile-config.js` file.

![image](https://cloud.githubusercontent.com/assets/506532/18660860/6dc1df32-7f1b-11e6-8403-157ce5b13b66.png)

**Comment by Jayuda** [comment]
Thanks, @AliMamed its works

**Comment by rahul606** [comment]
@povesteam your answer works for me. Thx
